/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedMeusPedidosRouteImport } from './routes/_authenticated/meus-pedidos'
import { Route as AuthenticatedVenderRouteImport } from './routes/_authenticated/vender'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as AuthenticatedPedidoIdRouteImport } from './routes/_authenticated/pedido.$id'
import { Route as ApiPublicPixChatRouteImport } from './routes/api/public/pix-chat'
import { Route as ApiPublicPixWebhookRouteImport } from './routes/api/public/pix-webhook'
import { Route as ApiPublicProductImageRouteImport } from './routes/api/public/product-image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusPedidosRoute =
  AuthenticatedMeusPedidosRouteImport.update({
    id: '/meus-pedidos',
    path: '/meus-pedidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVenderRoute = AuthenticatedVenderRouteImport.update({
  id: '/vender',
  path: '/vender',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPedidoIdRoute = AuthenticatedPedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPixChatRoute = ApiPublicPixChatRouteImport.update({
  id: '/api/public/pix-chat',
  path: '/api/public/pix-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixWebhookRoute = ApiPublicPixWebhookRouteImport.update({
  id: '/api/public/pix-webhook',
  path: '/api/public/pix-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductImageRoute = ApiPublicProductImageRouteImport.update({
  id: '/api/public/product-image',
  path: '/api/public/product-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/meus-pedidos': typeof AuthenticatedMeusPedidosRoute
  '/vender': typeof AuthenticatedVenderRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/pedido/$id': typeof AuthenticatedPedidoIdRoute
  '/api/public/pix-chat': typeof ApiPublicPixChatRoute
  '/api/public/pix-webhook': typeof ApiPublicPixWebhookRoute
  '/api/public/product-image': typeof ApiPublicProductImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/meus-pedidos': typeof AuthenticatedMeusPedidosRoute
  '/vender': typeof AuthenticatedVenderRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/pedido/$id': typeof AuthenticatedPedidoIdRoute
  '/api/public/pix-chat': typeof ApiPublicPixChatRoute
  '/api/public/pix-webhook': typeof ApiPublicPixWebhookRoute
  '/api/public/product-image': typeof ApiPublicProductImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRoute
  '/_authenticated/meus-pedidos': typeof AuthenticatedMeusPedidosRoute
  '/_authenticated/vender': typeof AuthenticatedVenderRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/_authenticated/pedido/$id': typeof AuthenticatedPedidoIdRoute
  '/api/public/pix-chat': typeof ApiPublicPixChatRoute
  '/api/public/pix-webhook': typeof ApiPublicPixWebhookRoute
  '/api/public/product-image': typeof ApiPublicProductImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/carteira'
    | '/meus-pedidos'
    | '/vender'
    | '/produto/$id'
    | '/pedido/$id'
    | '/api/public/pix-chat'
    | '/api/public/pix-webhook'
    | '/api/public/product-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/carteira'
    | '/meus-pedidos'
    | '/vender'
    | '/produto/$id'
    | '/pedido/$id'
    | '/api/public/pix-chat'
    | '/api/public/pix-webhook'
    | '/api/public/product-image'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/carteira'
    | '/_authenticated/meus-pedidos'
    | '/_authenticated/vender'
    | '/produto/$id'
    | '/_authenticated/pedido/$id'
    | '/api/public/pix-chat'
    | '/api/public/pix-webhook'
    | '/api/public/product-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  ApiPublicPixChatRoute: typeof ApiPublicPixChatRoute
  ApiPublicPixWebhookRoute: typeof ApiPublicPixWebhookRoute
  ApiPublicProductImageRoute: typeof ApiPublicProductImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-pedidos': {
      id: '/_authenticated/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof AuthenticatedMeusPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vender': {
      id: '/_authenticated/vender'
      path: '/vender'
      fullPath: '/vender'
      preLoaderRoute: typeof AuthenticatedVenderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pedido/$id': {
      id: '/_authenticated/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof AuthenticatedPedidoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/pix-chat': {
      id: '/api/public/pix-chat'
      path: '/api/public/pix-chat'
      fullPath: '/api/public/pix-chat'
      preLoaderRoute: typeof ApiPublicPixChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix-webhook': {
      id: '/api/public/pix-webhook'
      path: '/api/public/pix-webhook'
      fullPath: '/api/public/pix-webhook'
      preLoaderRoute: typeof ApiPublicPixWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/product-image': {
      id: '/api/public/product-image'
      path: '/api/public/product-image'
      fullPath: '/api/public/product-image'
      preLoaderRoute: typeof ApiPublicProductImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRoute
  AuthenticatedMeusPedidosRoute: typeof AuthenticatedMeusPedidosRoute
  AuthenticatedVenderRoute: typeof AuthenticatedVenderRoute
  AuthenticatedPedidoIdRoute: typeof AuthenticatedPedidoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRoute,
  AuthenticatedMeusPedidosRoute: AuthenticatedMeusPedidosRoute,
  AuthenticatedVenderRoute: AuthenticatedVenderRoute,
  AuthenticatedPedidoIdRoute: AuthenticatedPedidoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  ApiPublicPixChatRoute: ApiPublicPixChatRoute,
  ApiPublicPixWebhookRoute: ApiPublicPixWebhookRoute,
  ApiPublicProductImageRoute: ApiPublicProductImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
